project_id = "xfovfhhfarxmzsislbeb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.pooler]
enabled = false
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://xfovfhhfarxmzsislbeb.supabase.co"
additional_redirect_urls = [
  "https://xfovfhhfarxmzsislbeb.supabase.co/auth/v1/callback",
  "https://xfovfhhfarxmzsislbeb.supabase.co/**",
  "memoryos://login-callback/",
  "memoryos://login-callback",
  "memoryos://**",
]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
